# Generated by Django 4.1.6 on 2023-02-06 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=256)),
                ('link', models.CharField(max_length=128)),
                ('image', models.ImageField(upload_to='portfolio/')),
            ],
        ),
    ]
