# Generated by Django 4.1.6 on 2023-02-06 12:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio', '0002_myportfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='myportfolio',
            name='type',
            field=models.CharField(default=django.utils.timezone.now, max_length=4),
            preserve_default=False,
        ),
    ]
