# Generated by Django 4.1.6 on 2023-02-07 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio', '0003_myportfolio_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fish', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
            ],
        ),
    ]
