# Generated by Django 4.1.6 on 2023-02-07 07:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_portfolio', '0004_sendmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('blog_date', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('Web dasturlash', 'Web dasturlash'), ('Python', 'Python'), ('Deployment', 'Deployment')], max_length=28)),
                ('body', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
