# Generated by Django 4.1.6 on 2023-02-07 07:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio', '0006_blogs_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
